title: 小王子
description: 吳淡如人生不能沒故事：小王子
time: Mon, 25 Mar 2024 08:00:22 +0000
items:
  - title: 01. 小王子_之一
    size: 5796892
    duration: 359
  - title: 02. 小王子_之二
    size: 4995205
    duration: 312
  - title: 03. 小王子_之三
    size: 2099166
    duration: 131
  - title: 04. 小王子_之四
    size: 3731296
    duration: 233
  - title: 05. 小王子_之五
    size: 2883257
    duration: 180
  - title: 06. 小王子_之六
    size: 1107349
    duration: 69
  - title: 07. 小王子_之七
    size: 5635100
    duration: 352
  - title: 08. 小王子_之八
    size: 4547153
    duration: 284
  - title: 09. 小王子_之九
    size: 2051100
    duration: 128
  - title: 10. 小王子_之十
    size: 6035505
    duration: 377
  - title: 11. 小王子_之十一
    size: 2019340
    duration: 126
  - title: 12. 小王子_之十二
    size: 1059287
    duration: 66
  - title: 13. 小王子_之十三
    size: 4115405
    duration: 257
  - title: 14. 小王子_之十四
    size: 2403444
    duration: 150
  - title: 15. 小王子_之十五
    size: 3075104
    duration: 192
  - title: 16. 小王子_之十六
    size: 547287
    duration: 34
  - title: 17. 小王子_之十七
    size: 2291431
    duration: 143
  - title: 18. 小王子_之十八
    size: 595353
    duration: 37
  - title: 19. 小王子_之十九
    size: 1539104
    duration: 96
  - title: 20. 小王子_之二十
    size: 1443392
    duration: 90
  - title: 21. 小王子_之二十一
    size: 4755302
    duration: 297
  - title: 22. 小王子_之二十二
    size: 2056330
    duration: 128
  - title: 23. 小王子_之二十三
    size: 755433
    duration: 47
  - title: 24. 小王子_之二十四
    size: 2115472
    duration: 132
  - title: 25. 小王子_之二十五
    size: 2019342
    duration: 126
  - title: 26. 小王子_之二十六
    size: 3843315
    duration: 240
  - title: 27. 小王子_之二十七 ─ 完結篇
    size: 2419341
    duration: 151
